trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

resources:
  repositories:
  - repository: "Azure Repos Mirror"
    type: git
    name: efcore/efcore-ext

variables:
- group: azure-repos-sync

jobs:
- job: Build
  displayName: "Build, Test and Publish"

  pool:
    vmImage: windows-2022

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "> Setting up PostgreSQL"
        $postgresService = Get-Service postgresql* | select -First 1
        Set-Service -InputObject $postgresService -StartupType Manual
        net start $postgresService.Name
        Write-Host ""
        Write-Host "> Setting up MySQL"
        mysqld --initialize-insecure
        mysqld install
        $mysqlService = Get-Service mysql* | select -First 1
        net start $mysqlService.Name
        mysql -u root --skip-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Password12!'; FLUSH PRIVILEGES;"
        Write-Host ""
        Write-Host "> Listing .NET SDKs"
        dotnet --list-sdks
    displayName: 'Setup Environment'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
    displayName: 'Restore and Build Plugin'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--no-restore'
    displayName: 'Run Unit Tests'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '--no-restore -c Release -o $(Build.ArtifactStagingDirectory)'
    displayName: 'Package for NuGet'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'

- job: Sync
  displayName: "Sync with Azure Repos"

  pool:
    vmImage: windows-latest

  steps:
  - task: gitmirror@0
    inputs:
      GitRepoUrl: 'https://tlylz:$(SYNC_PAT)@dev.azure.com/tlylz/efcore/_git/efcore-ext'
    displayName: 'Sync via Git Tools'
